### ISSUE TITLE
TNT is too cheap.

### ISSUE THREAD

**Issue by jhcole** [FozLand/fozland#1]
My first thoughts are to either require a coal block instead of lump for gunpowder, or maybe fill the empty places in the tnt recipe with additional gunpowder. What do you think?

**Comment by mootpoint** [comment]
I like either coal block or using flint since it is randomly found in gravel

**Comment by jhcole** [comment]
Whatever we do, if we change it in the TNT, mod and we can't convince the upstream developers to pull it, then we will have to maintain a separate branch forever. So its best if we do the override here.

The only problem I see with coal block or flint in the gunpowder recipe is that it makes gunpowder alone expensive, which is a shame because gunpowder alone is interesting for long gunpowder trails. I think I like adding flint to the TNT recipe best.

Also I'm probably done until tomorrow. Taking the wife out.

**Comment by mootpoint** [comment]
All right I'll add that and see what I can do for a few other bugs tonight
it's pretty slow at work so I may be able to get some done

**Comment by mootpoint** [comment]
Currently on android: that being said I tried clear_craft , setting output too tnt:tnt 0 and just placing recipe in separate mod, new recipe works in all forms but so does old one. Let me know if you can fix this or if we need to keep forked branch of tnt. If we do the latter, I'll replace recipe any time tnt is updated.

**Comment by mootpoint** [comment]
Recipe will be nothing, flint, nothing
 wood, gunpowder, wood
Nothing, flint, Nothing. Let me know if that's alright

**Comment by jhcole** [comment]
The clear_craft line should look like this:
`minetest.clear_craft({output = 'tnt:tnt'})`

Requiring one flint is probably expensive enough.  I would like players to be able to use TNT for mining, I just don't want griefers who've joined 10 minutes ago to be able to blow up half the country side :).

With the new recipe for gravel, flint is essentially an infinite resource, but it requires digging 16 gravel on average for each one. Thats about 16 times more effort to make a tnt if using 1 flint, 32 times more if using 2.

Also, this makes the cost based on play time, instead of on item rarity. I like this because it seems to be more fair.

**Comment by mootpoint** [comment]
All right I'll write it up and test it and move it up here

**Comment by jhcole** [comment]
Fixed by 06a25bdab3154608cb2f991ce313fde3af5cd4f9
