### ISSUE TITLE
Issue: should be moved to channel mod

### ISSUE THREAD

**Issue by mootpoint** [FozLand/fozland#10]
First, Channel mod needs issue button.
Second, request feature for players with /ban or /judge to be able to /join <player> dating to put players who insist on dating after being warned by myself, hd and Candy_Perish to /join channel to continue dating talk. 
Will code if approved.

**Comment by jhcole** [comment]
Added an issue tracker to channels.

I would guess that players who are dating in global chat don't know how to use channels. Ideally, channels would have an easy to understand GUI, but that might be too ambitious. As long as we add a message telling them how to /leave the channel I'm willing to give this a try.

**Comment by mootpoint** [comment]
Thank you I will code as soon as I get done with sawables
