### ISSUE TITLE
Add AntiCursing Mod V1

### ISSUE THREAD

**Issue by mootpoint** [FozLand/fozland#3]
add anti cursing mod sends players to jail for 30 seconds upon cursing, there are some enhancements that will be added to this mod, but for now it is functional and test, and works with justice mod

mod can be found here : https://github.com/mootpoint/chat_anticurse

**Comment by mootpoint** [comment]
Added a few other english word, french and spanish words given courtesy mok, added in :)

**Comment by mootpoint** [comment]
decided to leave this up to judges

**Comment by jhcole** [comment]
I've been considering making global chat PG only. Instead of punishing users for swearing, just block the offending message and remind the user that global chat is PG.

Thoughts?

**Comment by mootpoint** [comment]
honestly if we remove all the extreme bad words. f, b, c. and the like, and leave the 'PG' rated ones like damn and hell, id be all right with that. or make an option that you can /join channel and be allowed to curse all you want

**Comment by mootpoint** [comment]
and honestly the only reason to send someone to jail for attempting to curse after that would be if they attempted to circumvent the ban in an obvious manner

**Comment by jhcole** [comment]
Sounds reasonable to me.

**Comment by mootpoint** [comment]
I did the rework to make mod limit to pg, sends reminder to player cursing is not allowed, but no jailtime. However i cannot find out if it removes message from chat or not.

**Comment by jhcole** [comment]
Added https://github.com/FozLand/chat_filter
