### ISSUE TITLE
Suggestion: Trick or Treat mod

### ISSUE THREAD

**Issue by mootpoint** [FozLand/fozland#4]
Allows players to hit a chest like node and it will give them candy, but only once on halloween. we can place multiple boxes and allow players to go "trick or treating"

**Comment by mootpoint** [comment]
https://github.com/mootpoint/trick_or_treat basic version of mod available

**Comment by jhcole** [comment]
I revised the history a bit and added the feature we discussed to prevent the last user from collecting candy again.
https://github.com/FozLand/trick_or_treat

**Comment by mootpoint** [comment]
Thank your so much.I should be back to normal playing and coding schedule
by wednesday
