### ISSUE TITLE
I Believe I Can Fly

### ISSUE THREAD

**Issue by jhcole** [FozLand/fozland#7]
Add auto fly granting privs when conditions are met:
first login over 60 days ago
8+ hours of time played
4+ land claims
1000+ nodes digged
1000+ nodes placed
?+ nodes crafted

Then jump out of the flight school airplane.

**Comment by mootpoint** [comment]
Line 183 set coordinates to -500, 1000, 500 for now, I'm making airplane there that is coordinates for front of plane. Will update with new coordinates when plane finished

**Comment by mootpoint** [comment]
500, 
1000, -500 sorry

**Comment by jhcole** [comment]
Wow, thats going to be huge!. I was picturing Cessna

**Comment by mootpoint** [comment]
Well... I was thinking 747 ;) well you can take mine down if you like

**Comment by mootpoint** [comment]
Added b something spirit
